/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-card": "#FFFFFF",
        "surface-container-highest": "#e4e2e4",
        "priority-hot": "#EF4444",
        "on-error-container": "#93000a",
        "on-primary-container": "#7c839b",
        "surface-dim": "#dcd9db",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f5",
        "on-tertiary-container": "#b87500",
        "on-surface": "#1b1b1d",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#fcf8fa",
        "outline-variant": "#c6c6cd",
        "tertiary-container": "#2a1700",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "status-drafted": "#8B5CF6",
        "secondary": "#0051d5",
        "background": "#fcf8fa",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#003ea8",
        "status-closed": "#64748B",
        "tertiary-fixed": "#ffddb8",
        "surface-tint": "#565e74",
        "on-secondary-fixed": "#00174b",
        "priority-cold": "#3B82F6",
        "on-surface-variant": "#45464d",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "surface-bg": "#F8FAFC",
        "error": "#ba1a1a",
        "on-secondary-container": "#fefcff",
        "primary-fixed": "#dae2fd",
        "secondary-fixed": "#dbe1ff",
        "status-contacted": "#10B981",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-surface": "#303032",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0f2",
        "surface": "#fcf8fa",
        "border-subtle": "#E2E8F0",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e4e2e4",
        "surface-container-high": "#eae7e9",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-container": "#f0edef",
        "on-secondary": "#ffffff",
        "primary-container": "#131b2e",
        "priority-warm": "#F97316",
        "status-new": "#6366F1",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#316bf3",
        "on-background": "#1b1b1d",
        "on-tertiary-fixed": "#2a1700",
        "outline": "#76777d"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-gap": "0.75rem",
        "container-margin": "2rem",
        "gutter": "1.5rem",
        "card-padding": "1.25rem",
        "section-gap": "2.5rem"
      },
      fontFamily: {
        h2: ["manrope", "sans-serif"],
        "data-mono": ["space-grotesk", "monospace"],
        "body-sm": ["inter", "sans-serif"],
        "body-base": ["inter", "sans-serif"],
        h1: ["manrope", "sans-serif"],
        h3: ["manrope", "sans-serif"],
        "label-caps": ["inter", "sans-serif"]
      },
      fontSize: {
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "1", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-base": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h3: ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
